#ansible module install nginx apt package
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

- name: "Install nginx"
  ansible.builtin.apt:
    name: nginx
    state: installed


#ansible copy from role ansible module
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy roboshop Config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf


#remove directory in ansible module
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html

- name: Clean Old App content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create app directory
  ansible.builtion.file:
    path: /usr/share/nginx/html
    state: directory

#download zip and extract in ansible module
#https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html

- name: Download App Content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes


- name: Start Nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true

